// Generated by gencpp from file rosserial_arduino/Power.msg
// DO NOT EDIT!


#ifndef ROSSERIAL_ARDUINO_MESSAGE_POWER_H
#define ROSSERIAL_ARDUINO_MESSAGE_POWER_H

#include <ros/service_traits.h>


#include <rosserial_arduino/PowerRequest.h>
#include <rosserial_arduino/PowerResponse.h>


namespace rosserial_arduino
{

struct Power
{

typedef PowerRequest Request;
typedef PowerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Power
} // namespace rosserial_arduino


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosserial_arduino::Power > {
  static const char* value()
  {
    return "b75f3bcdec2dcafb6503e9b6316400b0";
  }

  static const char* value(const ::rosserial_arduino::Power&) { return value(); }
};

template<>
struct DataType< ::rosserial_arduino::Power > {
  static const char* value()
  {
    return "rosserial_arduino/Power";
  }

  static const char* value(const ::rosserial_arduino::Power&) { return value(); }
};


// service_traits::MD5Sum< ::rosserial_arduino::PowerRequest> should match 
// service_traits::MD5Sum< ::rosserial_arduino::Power > 
template<>
struct MD5Sum< ::rosserial_arduino::PowerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosserial_arduino::Power >::value();
  }
  static const char* value(const ::rosserial_arduino::PowerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosserial_arduino::PowerRequest> should match 
// service_traits::DataType< ::rosserial_arduino::Power > 
template<>
struct DataType< ::rosserial_arduino::PowerRequest>
{
  static const char* value()
  {
    return DataType< ::rosserial_arduino::Power >::value();
  }
  static const char* value(const ::rosserial_arduino::PowerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosserial_arduino::PowerResponse> should match 
// service_traits::MD5Sum< ::rosserial_arduino::Power > 
template<>
struct MD5Sum< ::rosserial_arduino::PowerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosserial_arduino::Power >::value();
  }
  static const char* value(const ::rosserial_arduino::PowerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosserial_arduino::PowerResponse> should match 
// service_traits::DataType< ::rosserial_arduino::Power > 
template<>
struct DataType< ::rosserial_arduino::PowerResponse>
{
  static const char* value()
  {
    return DataType< ::rosserial_arduino::Power >::value();
  }
  static const char* value(const ::rosserial_arduino::PowerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSSERIAL_ARDUINO_MESSAGE_POWER_H
