// Generated by gencpp from file rosserial_arduino/TurnAngle.msg
// DO NOT EDIT!


#ifndef ROSSERIAL_ARDUINO_MESSAGE_TURNANGLE_H
#define ROSSERIAL_ARDUINO_MESSAGE_TURNANGLE_H

#include <ros/service_traits.h>


#include <rosserial_arduino/TurnAngleRequest.h>
#include <rosserial_arduino/TurnAngleResponse.h>


namespace rosserial_arduino
{

struct TurnAngle
{

typedef TurnAngleRequest Request;
typedef TurnAngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TurnAngle
} // namespace rosserial_arduino


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosserial_arduino::TurnAngle > {
  static const char* value()
  {
    return "2d11dcdbe5a6f73dd324353dc52315ab";
  }

  static const char* value(const ::rosserial_arduino::TurnAngle&) { return value(); }
};

template<>
struct DataType< ::rosserial_arduino::TurnAngle > {
  static const char* value()
  {
    return "rosserial_arduino/TurnAngle";
  }

  static const char* value(const ::rosserial_arduino::TurnAngle&) { return value(); }
};


// service_traits::MD5Sum< ::rosserial_arduino::TurnAngleRequest> should match 
// service_traits::MD5Sum< ::rosserial_arduino::TurnAngle > 
template<>
struct MD5Sum< ::rosserial_arduino::TurnAngleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosserial_arduino::TurnAngle >::value();
  }
  static const char* value(const ::rosserial_arduino::TurnAngleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosserial_arduino::TurnAngleRequest> should match 
// service_traits::DataType< ::rosserial_arduino::TurnAngle > 
template<>
struct DataType< ::rosserial_arduino::TurnAngleRequest>
{
  static const char* value()
  {
    return DataType< ::rosserial_arduino::TurnAngle >::value();
  }
  static const char* value(const ::rosserial_arduino::TurnAngleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosserial_arduino::TurnAngleResponse> should match 
// service_traits::MD5Sum< ::rosserial_arduino::TurnAngle > 
template<>
struct MD5Sum< ::rosserial_arduino::TurnAngleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosserial_arduino::TurnAngle >::value();
  }
  static const char* value(const ::rosserial_arduino::TurnAngleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosserial_arduino::TurnAngleResponse> should match 
// service_traits::DataType< ::rosserial_arduino::TurnAngle > 
template<>
struct DataType< ::rosserial_arduino::TurnAngleResponse>
{
  static const char* value()
  {
    return DataType< ::rosserial_arduino::TurnAngle >::value();
  }
  static const char* value(const ::rosserial_arduino::TurnAngleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSSERIAL_ARDUINO_MESSAGE_TURNANGLE_H
